dist: xenial
language: ruby
services: mongodb
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile
  - gemfiles/mongoid5.gemfile
rvm:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "jruby"
sudo: false
