language: ruby
install: 'bundle install && bundle exec rake appraisal:install'
services: mongodb
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - ree
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: ree
      gemfile: gemfiles/mongoid3.gemfile
