language: ruby
install: 'bundle install && bundle exec rake appraisal:install'
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  #- rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - ree
